services:
  backend:
    build:
      context: ../
      dockerfile: backend/Dockerfile
    image: tajii/spends-tracker:latest
    container_name: spends_tracker_backend
    ports:
      - '3031:8000'
    environment:
      - DATABASE_URL=sqlite+aiosqlite:////app/data/spends_tracker.db
      - HOST=0.0.0.0
      - PORT=8000
      - TZ=Europe/Berlin
    volumes:
      - ./data:/app/data # Custom path for persistent data
    restart: unless-stopped
