"""add tax_deductible to purchases

Revision ID: 3468abcae249
Revises: e1cd33416662
Create Date: 2026-01-30 11:13:05.930084

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3468abcae249'
down_revision = 'e1cd33416662'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###